-- Warranty / invoice management
CREATE TABLE IF NOT EXISTS warranties (
    id               INT AUTO_INCREMENT PRIMARY KEY,
    family_id        INT NOT NULL,
    user_id          INT NOT NULL,
    title            VARCHAR(255) NOT NULL,
    brand            VARCHAR(100) DEFAULT NULL,
    model            VARCHAR(100) DEFAULT NULL,
    serial_number    VARCHAR(100) DEFAULT NULL,
    store            VARCHAR(150) DEFAULT NULL,
    purchase_date    DATE         DEFAULT NULL,
    warranty_months  SMALLINT     NOT NULL DEFAULT 24,
    warranty_end_date DATE        DEFAULT NULL,
    price            DECIMAL(10,2) DEFAULT NULL,
    notes            TEXT         DEFAULT NULL,
    file_path        VARCHAR(500) DEFAULT NULL,
    file_original    VARCHAR(255) DEFAULT NULL,
    file_mime        VARCHAR(100) DEFAULT NULL,
    ocr_text         MEDIUMTEXT   DEFAULT NULL,
    created_at       DATETIME     DEFAULT CURRENT_TIMESTAMP,
    updated_at       DATETIME     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (family_id) REFERENCES families(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id)   REFERENCES users(id)    ON DELETE CASCADE,
    FULLTEXT KEY ft_warranties (title, brand, model, serial_number, store, ocr_text)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
